# Generated by Django 5.1.5 on 2025-04-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usern', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
