# Generated by Django 5.1.5 on 2025-04-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_userdata2_alter_userdata_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata2',
            old_name='usern',
            new_name='username',
        ),
    ]
