# Generated by Django 5.1.5 on 2025-05-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_to_cart',
            field=models.BooleanField(default=False),
        ),
    ]
